version: '3.8'
services:
  inventorydetails:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - '5009:8080'
    networks:
      - net1

  inventorydetails2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - '5010:8080'
    networks:
      - net1

  sql-server-db:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Admin@123"
      ACCEPT_EULA: "Y"
    networks:
      - net1

networks:
  net1:
